# Generated by Django 4.1.1 on 2022-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_id_user__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
    ]
